### ISSUE TITLE
Cannot detect HP/MP after today's upgraded

### ISSUE THREAD

**Issue by wigcheng** [panex0845/LineageW#3]
As title, I think should be need change memory address, but I don't know how to do it,  please give me some directions or setting rule, thx.

**Comment by wigcheng** [comment]
Try to use CheatEngine to get address but NC shows detect hack.... so no other ways?

**Comment by panex0845** [comment]
Yes, it need to change localplayer's pointer in every game version upgrade.

Almost all online gane have anti-cheat system, and then CheatEngine is in black list already.  You need to change feature code to bypass it.

**Comment by wigcheng** [comment]
I start worry about maybe my acc will be blocked becasue the game just scan my hack behavior :)
How do you think?

I have no special featured CE version, could you shrare with me, my LINE ID is love_mayqueen

BTW I think wait your upgrade is more safety XDDD

**Comment by panex0845** [comment]
CheatEngine is the most outstanding external debugger tool.  No one can prove what is it doing if you didnt inject/hook something in the game progress.

In my opinion, repleace the feature code and build CE source code by yourself  is the way for relative safety.

**Comment by wigcheng** [comment]
Thanks for your detail explain!!
I found source code:
https://github.com/cheat-engine/cheat-engine

I'll compile it later, but do you know where can get bypass feature patches?

Thanks

**Comment by wigcheng** [comment]
Hi, I have a stupid question about NC start lock accounts which using plug-in such as Assistant, etc.

Do you think is it possible to lock users which use this open source plug-in? I don't know Assistant's structure but should be the same method - memory address loading to get specific values, low risk method could be use screen capture to get the pixels but bad performance...

How do you think? Thanks

**Comment by panex0845** [comment]
I have quit from LineageW already.  

As far as I know, Assistant hook game to get/send game functions via ![ws2_32.dll proxy](https://github.com/fatrolls/WS2_32-Proxy-DLL).

Besides, all the hacks are not 100% safe. Dont be afraid if you use hack; Dont use hack if you afraid to get banned.

**Comment by wigcheng** [comment]
That is bad news, I still wait for you update on every Wednesday :), so it means you should don't update this repo anymore, right?

**Comment by wigcheng** [comment]
I try to learn tonight but always get detect hacked and close the LinW (at least 10 times) :( , hope my acc still safe....

I follow this video to chagne the CE source code to avoid LINW detect but still failed,
https://www.youtube.com/watch?v=X0lMBRaZgL4

Do you have any ideas about I missing something? I'm pretty sure my execue file has no any cheat engine string... thx

**Comment by panex0845** [comment]
![Here is the BEST WAY to learn about game hacking as I know.](https://guidedhacking.com/forums/the-game-hacking-bible-learn-how-to-hack-games.469/) 

Don't google for free lesson, it will only waste your time then get nothing.

**Comment by wigcheng** [comment]
I appreciate for your update this repo! Because I still stuck CE hacking ( normal days is super busy on job), and it seems still need some effort.

So I must say thank you again for let this repo keep going!
